name: dart_quic
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  encrypt: ^5.0.3
  crypto: ^3.0.3
  x509: ^0.2.4+3
  convert: ^3.1.1
  cryptography: ^2.7.0
  hex: ^0.2.0
  collection: ^1.18.0
  x25519: ^0.1.1
  ecdsa: ^0.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.2

# Add this entire section to the end of the file
dependency_overrides:
  pointycastle: 3.7.4