name: dart_quic
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  pointycastle: ^4.0.0
  crypto: ^3.0.6
  x509: ^0.2.4+3
  convert: ^3.1.2
  cryptography: ^2.7.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
